### PR TITLE
Diagnostics improvements

### PR DESCRIPTION
**Pull request by larsbrinkhoff**

### CODE REVIEW

**Comment by larsbrinkhoff** [comment]
Can `--loglevels CPU0:6` replace the `cprint_all` stuff?

**Comment by stefanberndtsson** [comment]
Yes, I think CPU0:6 is reasonable for that.

**Comment by larsbrinkhoff** [comment]
Ok, I added a commit to remove the old `cprint_all` stuff.

**Comment by stefanberndtsson** [comment]
Did you intend to do the toggle before I merge?

**Comment by larsbrinkhoff** [comment]
No, that was not my intention.  I think that may be easier after a rework to make diagnostics part of a `struct device` thing.

**Pull request merged**
